### ISSUE TITLE
Swap preact-signal-store out for @deepsignal/react

### ISSUE THREAD

**Issue by EthanStandel** [capitalch/bika#1]
Hi there! Github recently put a badge on my `EthanStandel/preact-signal-store` repo that said this was a dependent. I went to look at your project and saw that you were using _React_ and not _Preact_ which `preact-signal-store` did not support (it only integrated with `@preact/signals` which is a Preact specific package). However, last night I completed the rebranding of `preact-signal-store` to a series of packages under the `@deepsignal/*` organization on NPM.

So, if you want to use a fully Signal driven state management solution for React, you can now use `@deepsignal/react` which is based off `@preact/signals-react`! It should be a simple drop-in-replacement for anything you may have tried to do with it previously (and now it will actually work in your use-case). 🙂

**Comment by capitalch** [comment]
Thanks,
It would be of great help
Sushant

**Comment by EthanStandel** [comment]
Looks like this is good to go!
